apiVersion: apps/v1  
kind: Deployment  
metadata:  
  name: app-reverse-proxy
  labels:
    app: app-reverse-proxy
    category: reverse-proxy
spec:  
  replicas: {{ .Values.reverseProxy.deployment.replicaCount }}
  selector:
    matchLabels:
      app: app-reverse-proxy
  template:
    metadata:
      labels:
        app: app-reverse-proxy
        category: reverse-proxy
    spec:
      containers:
      - name: app-reverse-proxy
        image: {{ .Values.reverseProxy.deployment.repository }}:{{ .Values.reverseProxy.deployment.tag }}
        ports:
        - containerPort: {{ .Values.reverseProxy.service.internalPort }}
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 100m
            memory: 50Mi
        volumeMounts:
        - name: app-rp-config-cm-vol
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
          readOnly: true
        - name: app-rp-config-cm-vol
          mountPath: /etc/nginx/conf.d/app.conf
          subPath: app.conf
          readOnly: true
      volumes:
      - configMap:
          name: app-rp-config-cm
          items:
          - key: nginx.conf
            path: nginx.conf
          - key: app.conf
            path: app.conf
        name: app-rp-config-cm-vol
