apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: {{ .Values.database.deployment.repository }}:{{ .Values.database.deployment.tag }}
          env:
           - name: MYSQL_ROOT_PASSWORD
             value: {{ .Values.database.deployment.rootPassword }}
          ports:
           - name: mysql
             containerPort: {{ .Values.database.service.internalPort }}
          volumeMounts:
           - name: mysql-persistent-storage
             mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim

