apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: {{ .Values.namespace }}
  labels:
    app: phpmyadmin
spec:
  replicas: {{ .Values.phpmyadmin.deployment.replicaCount }}
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: {{ .Values.phpmyadmin.deployment.repository }}:{{ .Values.phpmyadmin.deployment.tag }}
        env:
          - name: PMA_HOST
            value: mysql-service.default.svc.cluster.local
        ports:
        - containerPort: {{ .Values.phpmyadmin.service.internalPort }}
