apiVersion: v1  
kind: Service  
metadata:  
  name: app-reverse-proxy
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.reverseProxy.service.type }}
  ports:
  - name: http
    protocol: {{ .Values.reverseProxy.service.protocol }}
    targetPort: {{ .Values.reverseProxy.service.internalPort }}
    port: {{ .Values.reverseProxy.service.externalPort }}
  selector:
    app: app-reverse-proxy
    category: reverse-proxy
