apiVersion: v1  
kind: Service  
metadata:  
  name: app-reverse-proxy
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - name: http
    targetPort: 80
    port: 80
  selector:
    app: app-reverse-proxy
    category: reverse-proxy
