apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: mysql
  type: {{ .Values.database.service.type }}
  ports:
  - protocol: {{ .Values.database.service.protocol }}
    port: {{ .Values.database.service.externalPort }}
    targetPort: {{ .Values.database.service.internalPort }}
