apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: phpmyadmin
  type: {{ .Values.phpmyadmin.service.type }}
  ports:
  - protocol: {{ .Values.phpmyadmin.service.protocol }}
    port: {{ .Values.phpmyadmin.service.externalPort }}
    targetPort: {{ .Values.phpmyadmin.service.internalPort }}
