apiVersion: v1  
kind: ConfigMap  
metadata:  
  name: app-rp-config-cm
  namespace: {{ .Values.namespace }}
data:  
  nginx.conf: |
    user www-data;
    worker_processes auto;
    pid /run/nginx.pid;
    events {
        worker_connections 1024;
    }
    http {
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        keepalive_timeout 65;
        types_hash_max_size 2048;
        include /etc/nginx/mime.types;
        default_type application/octet-stream;
        error_log /var/log/nginx/error.log;
        include /etc/nginx/conf.d/app.conf;
    }
  app.conf: |
    upstream app {
      server phpmyadmin-service.default.svc.cluster.local:8080;
      keepalive 15;
    }
    server {
      listen 80;
      server_name _;
      location / {
        proxy_pass http://app;
        proxy_set_header Connection "Keep-Alive";
        proxy_set_header Proxy-Connection "Keep-Alive";
        proxy_redirect off;
      }
    }
